app/authentication/routes.py
from forms import UserSignUpForm, UserSigninForm
from models import User, db, check_password_hash
from flask import Blueprint, render_template, request, redirect, url_for, flash


# imports for flask login
from flask_login import login_user, logout_user, LoginManager, current_user, login_required


auth = Blueprint('auth', __name__, template_folder='auth_templates')

@auth.route('/signup', methods = ['GET', 'POST'])
def signup():
    form = UserSignUpForm()

    try:
        if request.method == 'POST' and form.validate_on_submit():
            first_name = form.first_name.data
            last_name = form.last_name.data
            username = form.username.data
            email = form.email.data
            password = form.password.data
            print(email, first_name, last_name, username, password)

            user = User(first_name, last_name, username, email, password = password)

            db.session.add(user)
            db.session.commit()

            flash(f'You have successfully created a user account {email}', 'User-created')
            return redirect(url_for('site.home'))
            
            
            
    except:
        raise Exception('Invalid form data: Please check your form')
    return render_template('signup.html', form=form)


@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    form = UserSigninForm()
    
    try:
        if request.method == 'POST' and form.validate_on_submit():
            username = form.username.data
            password = form.password.data
            print(username, password)

            logged_user = User.query.filter(User.username == username).first()
            if logged_user and check_password_hash(logged_user.password, password):
                login_user(logged_user)
                flash('You were successful in your login. Congratulations, and welcome to the Book Search Page.', 'auth-success')
                return redirect(url_for('site.profile'))
            else:
                flash('You do not have access to this site because you are not properly authorized.', 'auth-failed')
                return redirect(url_for('auth.signin'))
    except:
        raise Exception('Invalid Form Data: Please Check your Form and Validate Your Information.')
    return render_template('signin.html', form=form)

@auth.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('site.home'))

app/site/routes.py
from flask import Blueprint, request, jsonify, render_template, redirect, flash, url_for
from flask_login import current_user, login_required
from helpers import token_required
from models import db, User, Book, book_schema, books_schema
import requests 

site = Blueprint('site', __name__, template_folder='site_templates')

@site.route('/')
def home():
    return render_template('index.html')

@site.route('/profile')
@login_required
def profile():
    return render_template('profile.html')

@site.route('/books')
@login_required
def books():
    books = Book.query.all()
    return render_template('books.html', books=books)

@site.route('/create_book', methods=['POST'])
def create_book():
    isbn = request.form['isbn']
    title = request.form['title']
    author = request.form['author']
    length = request.form['length']
    cover = request.form['cover']
    copyright = request.form['copyright']
    description = request.form['description']
    user_token = current_user.token
    
    book = Book(isbn, title, author, length, cover, copyright, description, user_token = user_token)
    
    db.session.add(book)
    db.session.commit()
    
    return redirect(url_for('site.books'))


# @site.route('/search')
# def search():

#     return render_template('search.html')


# @site.route('/<int:id>/update', methods=['GET','PUT', 'POST'])
# def update(id):
#     # isbn = current_user.isbn
#     # book = Book.query.get(isbn)
    
    
#     user_id = current_user.id
#     book = Book.query.filter_by(user_id=user_id).first()
    
#     if request.method == 'PUT':
#         isbn = request.form['isbn']
#         title = request.form['title']
#         author = request.form['author']
#         length = request.form['length']
#         cover = request.form['cover']
#         copyright = request.form['copyright']
#         description = request.form['description']
        
        
#         book.isbn = isbn
#         book.title = title
#         book.author = author
#         book.length = length
#         book.cover = cover
#         book.copyright = copyright
#         book.description = description
        
#         db.session.add(book)
#         db.session.commit()
        
#         return redirect(url_for('site.books'))
    
    
#     return redirect(url_for('site.books'))
    
    # book = Book.query.get_or_404(isbn)
    # if not request.form:
    #     abort(404)
        
    # book = Book.query.get(isbn)
    # if book is None:
    #     abort(404)
        
    # book.isbn = request.form.get('isbn', book.isbn)
    # book.title = request.form.get('title', book.title)
    # book.author = request.form.get('author', book.author)
    # book.length = request.form.get('length', book.length)
    # # book.cover = request.form.get('cover', book.cover)
    # book.copyright = request.form.get('copyright', book.copyright)
    # book.description = request.form.get('description', book.description)
    # db.session.commit()
    # return redirect(url_for('site.books'))

# ('/<int:id>/update', methods=['GET','POST'])
# def update(id):
#     user_id = current_user.id
#     book = Book.query.filter_by(user_id=user_id).first()

#     return redirect(url_for('site.update', book = book))


@site.route('/update/<string:id>', methods=['POST', 'PUT'])
@login_required
def update(id):
    # book = Book.query.get_or_404(id)
    book = Book.query.get(id)
    # if 'isbn' in request.form:
    #     i.isbn = request.form['isbn']
    # db.session.commit()
    
    
    # user_id = current_user.id
    # book = Book.query.filter_by(isbn=isbn).first()
    # book = Book.query.get(isbn)
    
    # book = Book.query.filter_by(id=id).first()
    # form = BookForm(obj=book)
    # id = current_user.id
    # if request.method == 'POST':
        # db.session.delete(book)
        # db.session.commit()
        # if book:
    isbn = request.form['isbn']
    title = request.form['title']
    author = request.form['author']
    length = request.form['length']
    cover = request.form['cover']
    copyright = request.form['copyright']
    description = request.form['description']
        
        # book.isbn = isbn
        # book.title = title
        # book.author = author
        # book.length = length
        # book.cover = cover
        # book.copyright = copyright
        # book.description = description
                
    book = Book(
        isbn = isbn,
        title = title,
        author =author,
        length = length,
        cover = cover,
        copyright = copyright,
        description = description
    )

    db.session.update(book)
    db.session.commit()
    return redirect(url_for('site.books'))
    #     return f"There is no book with isbn: {isbn}."
        
    # return redirect(url_for('site.books'))


# return redirect(url_for('site.books'))

# @site.route ('/<int:isbn>/update', methods= ['PUT'])
# def update(isbn):
#     if not request.form:
#         abort(400)
#     book = Book.query.get(isbn)
#     if book is None:
#         abort(404)
#     book.isbn = request.form.get('isbn', book.isbn)
#     book.title = request.form.get('title', book.title)
#     book.author = request.form.get('author', book.author)
#     book.length = request.form.get('length', book.length)
#     book.cover = request.form.get('cover', book.cover)
#     book.copyright = request.form.get('copyright', book.copyright)
#     book.description = request.form.get('description', book.description)
#     db.session.commit()
#     return redirect(url_for('site.books'))



@site.route('/', methods=[' GET'])
def retrieveBookList():
    books = Book.query.all()
    return render_template('index.html', books = books)



@site.route('/delete/<id>', methods=['GET','POST'])
def delete(id):
    books = Book.query.get(id)
    if request.method == 'POST':
        if books:
            db.session.delete(books)
            db.session.commit()
            return redirect(url_for('site.books'))
        abort(404)
    return render_template('site.books')
    

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Book Inventory" content="Book Inventory"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
<link rel="stylesheet" href="../static/css/styles.css">
<script src="https://kit.fontawesome.com/63b7bba61e.js" crossorigin="anonymous"></script>
<link rel="stylesheet" href="../static/css/styles.css">
<title>Find Your Books</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg  navbar-info py-2.5  fixed-top">
        
        <div class="container">
            <a href="{{ url_for('site.home') }}" class="navbar-brand">Find Your Books</a>
            <button 
                class="navbar-toggler" 
                type="button" 
                data-bs-toggle="collapse" 
                data-bs-target="#navmenu"
            ><i class="fa-regular fa-bars fa-bounce"></i>
            </button>
            <div class="collapse navbar-collapse" id="navmenu">
                <ul class="navbar-nav ms-auto d-fles flex-row">
                    <li class="nav-item">
                        <a href="{{ url_for('site.home') }}" class="nav-link">Home</a>
                    </li>
                    {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{{ url_for('site.profile') }}" class="nav-link">Profile</a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ url_for('site.books') }}" class="nav-link">Books</a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ url_for('auth.logout') }}" class="nav-link">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a href="{{ url_for('auth.signup') }}" class="nav-link">Sign Up</a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ url_for('auth.signin') }}" class="nav-link">Sign In</a>
                    </li>
                    {% endif %}
                    
                </ul>
            </div>
        </div>
    </nav>
    
        
<!--  -->
{% block content %}
{% endblock %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/js/bootstrap.min.js"></script>
</body>
</html>

app/templates/forms.html
<form method="POST">
    
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="first_name-field">
            {{ form.first_name.label }}
            {{ form.first_name(class = "form-control", placeholder = "First Name") }}
        </fieldset>
    </div>
    <div class="form-group">
        <fieldset id="last_name-field">
            {{ form.last_name.label }}
            {{ form.last_name(class = "form-control", placeholder = "Last Name") }}
        </fieldset>
    </div>
    <div class="form-group">
        <fieldset id="username-field">
            {{ form.username.label }}
            {{ form.username(class = "form-control", placeholder = "Enter Username") }}
        </fieldset>
    </div>
    <div class="form-group">
        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class = "form-control", placeholder = "Enter Email") }}
        </fieldset>
    </div>
    
    <fieldset id="pass-field">
        {{ form.password.label }}
        {{ form.password(class = "form-control", placeholder = "Enter Password") }}
    </fieldset>
        <!-- Submit button area -->
        {{ form.submit_button(class = "btn btn-primary btn-block mt-2")}}

</form>